### ISSUE TITLE
DRl文件

### ISSUE THREAD

**Issue by ZhangLong-9527** [XYndzq/FreeJLC#1]
我想问一下,嘉立创的Gerber里面有几个DRL文件,但是ad里面没有,你程序生成的时候也没有,貌似没有这个文件不能进行免费白嫖

**Comment by XYndzq** [comment]
DRL是钻孔文件，在AD中导出Gerber文件后需要单独导出钻孔文件，将Gerber文件和DRL文件放到一个文件夹才能发给板厂正常生产，这个文件是不需要脚本转换的，其他文件转换成功后打包上传就可以。
